### PR TITLE
Fix issues found by ansible-test and linters - enable all tests on all repos - remove suppressions

### PR DESCRIPTION
**Pull request by nhosoi**
- Cleaning up ansible-lint errors
- Cleaning up ansible-test errors future-import-boilerplate and metaclass-boilerplate
    
Note:
    In terms of the two items in the ansible-test ignore file
    - plugins/modules/kernel_settings.py validate-modules:parameter-type-not-in-doc
    - plugins/modules/kernel_settings.py validate-modules:undocumented-parameter
    they are needed since parameters modules, selinux, systemd and vm are not
    intentionally documented.

@richm, I also would like to double-check that `validate-modules:module-invalid-version-added` is not needed for ansible 2.9, but for 2.10. Thanks!
```
--- .sanity-ansible-ignore-2.10.txt	2021-03-31 14:53:44.285830511 -0700
+++ .sanity-ansible-ignore-2.9.txt	2021-03-31 13:28:14.691715762 -0700
@@ -3,5 +3,4 @@
 tests/kernel_settings/run_ansible_for_testing.sh shebang!skip
 plugins/modules/kernel_settings.py validate-modules:missing-gplv3-license
 plugins/modules/kernel_settings.py validate-modules:parameter-type-not-in-doc
 plugins/modules/kernel_settings.py validate-modules:undocumented-parameter
-plugins/modules/kernel_settings.py validate-modules:module-invalid-version-added
```

### CODE REVIEW

**Comment by richm** [comment]
> @richm, I also would like to double-check that validate-modules:module-invalid-version-added is not needed for ansible 2.9, but for 2.10. Thanks!

I think that's correct. I think they changed module-invalid-version-added in 2.10.

**Comment by nhosoi** [comment]
I think the CI failure with `rhel-x/ansible-2.9` is covered by bz for RHEL9, but not certain about `centos-8/ansible-2.9`, etc.

**Comment by richm** [comment]
> I think the CI failure with `rhel-x/ansible-2.9` is covered by bz for RHEL9, but not certain about `centos-8/ansible-2.9`, etc.

Error uploading results :-( we have the fedorapeople.org problem again . . .

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest pending]

**Comment by nhosoi** [comment]
> > I think the CI failure with `rhel-x/ansible-2.9` is covered by bz for RHEL9, but not certain about `centos-8/ansible-2.9`, etc.
> 
> Error uploading results :-( we have the fedorapeople.org problem again . . .

Thank you, @richm. Now the uploading the CI result issue is solved and it looks good!

**Review by richm — APPROVED** [review]
lgtm

**Pull request merged**
